version: '3.8'
services:

  auth-demo-frontend:
    build:
      context: https://github.com/tanmayvaij/auth-demo-frontend.git
    container_name: auth-demo-frontend
    ports:
      - 8080:8080
    environment:
      - REACT_APP_BACKEND_URL=http://auth-demo-backend:${BACKEND_EXPOSE_PORT}
    depends_on:
      - auth-demo-backend
    restart: unless-stopped

  auth-demo-backend:
    build:
      context: https://github.com/tanmayvaij/auth-demo-backend.git
    container_name: auth-demo-backend
    ports:
      - ${BACKEND_EXPOSE_PORT}:${BACKEND_EXPOSE_PORT}
    environment:
      - MONGO_URI=mongodb://db:27017/authdemodb
      - BACKEND_EXPOSE_PORT=${BACKEND_EXPOSE_PORT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mongo
    container_name: db
    ports:
      - 27017:27017
    restart: unless-stopped
      
networks:
  default:
    name: auth-demo-stack-network
